### ISSUE TITLE
MOD SHIELD CRASHING 1.19.4 (can you please check it carefully since this bug happened to a normal shield)

### ISSUE THREAD

**Issue by makumaku1974** [SolipIngen/minecraft.sassot#33]
[crash-2023-05-06_15.27.43-server.txt](https://github.com/SolipIngen/minecraft.sassot/files/11411781/crash-2023-05-06_15.27.43-server.txt)
[crash-2023-05-06_14.59.48-server.txt](https://github.com/SolipIngen/minecraft.sassot/files/11411782/crash-2023-05-06_14.59.48-server.txt)

Two of this files occured by two mobs that hit my Vanilla shield. I have not tried using your modded shields yet since the recipes felt cheap. must be revamped. Also, the mod seems perfect and did not know there was difficulty involved in this mod.

**Comment by SolipIngen** [comment]
Thank you for reporting this issue. It was a silly casting oversight; it's now fixed and the vanilla Shield should also work fine with the modded enchantments. The updated version should be online soon. If any other issues arise, please let me know.

As for your feedback on the modded Shield recipes, would you perhaps make that feedback as a comment on CurseForge/Modrinth? I personally think it'd be great if other players could directly see all content feedback.
That being said, Framed Shields may be a bit cheap as the Framing Template does require only wood and sticks. The solid Shields are worth the same as Leggings of their material, which I deemed to be a good price. If you have any suggestions on this, please feel free to comment on the posted mod pages.
