### ISSUE TITLE
Incompatible with Mythic Metals

### ISSUE THREAD

**Issue by Omni-MC** [SolipIngen/minecraft.sassot#45]
Did some poking around looking for forks of AdditionalEntityAttributes and found the Mythic Metals dev forked it. Removing Mythic Metals solves the crash.
The mod crashes on startup when Mythic Metals is installed

To reproduce: Install SASSOT alongside Mythic Metals and attempt to load the game

Log- https://mclo.gs/HtQT4kK

Versions-
MC: 1.19.4
Fabric Loader: 0.14.19
Fabric API: 0.81.1
Mythic Metals: 0.17.6
SASSOT: 1.0.0

**Comment by SolipIngen** [comment]
Thank you for writing in. 
v1.0.1 should now be compatible with Mythic Metals, and any other mod that uses @ModifyConstant to change the critical attack damage multiplier. Please let me know if this has resolved the issue on your end as well.

**Comment by MClapClap** [comment]
Hello in the new version 1.20.1 Mythic metals is incompatible again with SASSOT, same reason.

**Comment by SkinlesSpartan** [comment]
I am having the same problem on 1.20.1

**Comment by SolipIngen** [comment]
Thank you all for reporting this issue. This issue should now have been solved in the latest v1.1.3-1.20.1(+bettercombat) versions. This thread will now be closed, please feel free to report any persisting issues in the future.
