### ISSUE TITLE
Throwing mixin injection error with Origins and other mods

### ISSUE THREAD

**Issue by xyxt1c** [SolipIngen/minecraft.sassot#52]
SASSOT 1.1.0-1.1.2 seem to have problems with Origins and also pehkui, both the normal and bettercombat versions affected. This mixin error happens with multiple mods with the exact same output but out of my actual modpack I only narrowed down the two mentioned above so far.

> Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at net.minecraft.class_2966.method_12851(class_2966.java:54)
> 	at net.minecraft.client.main.Main.main(Main.java:166)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
> 	... 9 more
> **Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifiedSweepingRange(D)D in sassot.mixins.json:entity.player.PlayerEntityMixin from mod sassot failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap sassot-refmap.json**
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
> 	... 12 more
>

**Comment by Zbas01** [comment]
Same with pehkui

**Comment by SrGnis** [comment]
This also happen with the mod Things, seems that the problem is a mixin conflict with the library [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes). A quick search in github shows that this library is used in a lot of mods.

And probably #45 is related to this.

**Comment by SolipIngen** [comment]
Thank you all for reporting this issue. This issue should now have been solved in the latest v1.1.3-1.20.1(+bettercombat) versions. 
As mentioned by SrGnis, the solution for vanilla SASSOT using the Reach Entity Attributes library. Crash issues from the +bettercombat version have also been fixed. 
This thread will now be closed, please feel free to report any persisting issues in the future.
